### ISSUE TITLE
Client example no longer compiles

### ISSUE THREAD

**Issue by alfiedotwtf** [snapview/tokio-tungstenite#70]
I know that there's been big changes since Tokio moving point releases, but thought I'd point out the obvious that `examples/client.rs` no longer compiles:

    error[E0432]: unresolved import `futures::sync`
    use futures::sync::mpsc;

    error[E0425]: cannot find function `run` in module `tokio::runtime`
    tokio::runtime::run(client.map_err(|_e| ()));

    error: the `and_then` method cannot be invoked on a trait object
    let client = connect_async(url).and_then(move |(ws_stream, _)| {

**Comment by sdroege** [comment]
That's entirely expected. See https://github.com/snapview/tokio-tungstenite/pull/68 for branches that work with tokio 0.2.0-alpha and the 0.2.0 release.

**Comment by alfiedotwtf** [comment]
Ah awesome, thanks for that!

**Comment by application-developer-DA** [comment]
I think this is not relevant anymore.
